### ISSUE TITLE
Error [INVALID_INTENTS]: [Bot Token] Invalid intent provided for WebSocket intents

### ISSUE THREAD

**Issue by wibuf** [crimilo/Discord-Mirror#29]
Think there may have been a change to Discord, seeing this in an older version of Discord-Mirror and the latest:

`C:\Users\nicho\Desktop\PycharmProjects\optionBot\Discord-Mirror>npm start

> start
> node dist/index.js

(node:19220) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
C:\Users\nicho\Desktop\PycharmProjects\optionBot\Discord-Mirror\node_modules\discord.js-selfbot-v13\src\client\websocket\WebSocketManager.js:265
        throw new Error(WSCodes[error.code]);
              ^

Error [INVALID_INTENTS]: [Bot Token] Invalid intent provided for WebSocket intents.
    at WebSocketManager.createShards (C:\Users\nicho\Desktop\PycharmProjects\optionBot\Discord-Mirror\node_modules\discord.js-selfbot-v13\src\client\websocket\WebSocketManager.js:265:15)
    at async MirrorClient.login (C:\Users\nicho\Desktop\PycharmProjects\optionBot\Discord-Mirror\node_modules\discord.js-selfbot-v13\src\client\Client.js:342:7) {
  [Symbol(code)]: 'INVALID_INTENTS'
}

Node.js v21.1.0`

I've tried updating Node, as well as creating a new bot token, as well as verifying that all the Intents in Discord Developer Portal are enabled for my bot. This was fully working yesterday with no changes to my discord bot until I saw these errors this morning. 

Thanks

**Comment by wibuf** [comment]
Figured it out, my user token seems to have changed
