### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by louanfontenele** [crimilo/Discord-Mirror#5]
```txt
/home/container/discordMirror.js:60
    for (const webhookUrl of mirror['webhooks_urls']) {
                                   ^
TypeError: mirror.webhooks_urls is not iterable
    at loadConfigValues (/home/container/discordMirror.js:60:36)
    at Object.<anonymous> (/home/container/discordMirror.js:81:1)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1219:10)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47
```

**Comment by louanfontenele** [comment]
My bad, sorry. I fixed.
