### ISSUE TITLE
Error mirroing certain embeds

### ISSUE THREAD

**Issue by z0mbieboss** [crimilo/Discord-Mirror#51]
Hello 
i a noob when it comes to coding and running scripts so i have a hard time understanding the error. 
Problem:

Normal messasges gets mirrored with no problem but some embeded messages cant be mirrored and the script shows following error:

RangeError [EMBED_FIELD_VALUE]: MessageEmbed field values must be non-empty strings.
    at Util.verifyString (C:\Users\Administrator\Desktop\FINALL\Discord-Mirror-main\node_modules\discord.js-selfbot-v13\src\util\Util.js:462:49)
    at MessageEmbed.normalizeField (C:\Users\Administrator\Desktop\FINALL\Discord-Mirror-main\node_modules\discord.js-selfbot-v13\src\structures\MessageEmbed.js:555:19)
    at C:\Users\Administrator\Desktop\FINALL\Discord-Mirror-main\node_modules\discord.js-selfbot-v13\src\structures\MessageEmbed.js:576:14
    at Array.map (<anonymous>)
    at MessageEmbed.normalizeFields (C:\Users\Administrator\Desktop\FINALL\Discord-Mirror-main\node_modules\discord.js-selfbot-v13\src\structures\MessageEmbed.js:575:8)
    at MessageEmbed.setup (C:\Users\Administrator\Desktop\FINALL\Discord-Mirror-main\node_modules\discord.js-selfbot-v13\src\structures\MessageEmbed.js:107:91)
    at new MessageEmbed (C:\Users\Administrator\Desktop\FINALL\Discord-Mirror-main\node_modules\discord.js-selfbot-v13\src\structures\MessageEmbed.js:45:10)
    at C:\Users\Administrator\Desktop\FINALL\Discord-Mirror-main\node_modules\discord.js-selfbot-v13\src\structures\MessagePayload.js:264:49
    at Array.map (<anonymous>)
    at MessagePayload.resolveData (C:\Users\Administrator\Desktop\FINALL\Discord-Mirror-main\node_modules\discord.js-selfbot-v13\src\structures\MessagePayload.js:264:36) {
  [Symbol(code)]: 'EMBED_FIELD_VALUE'

if anyone could help me solve this i would be happy to tip you :)

**Comment by crimilo** [comment]
Hi, are you using the latest version of the bot?

I should have fixed this error 3 commits ago.

**Comment by belg1o** [comment]
> Hi, are you using the latest version of the bot?
> 
> I should have fixed this error 3 commits ago.

I'm still getting an error similar to this on the latest commit. 

RangeError [EMBED_FIELD_NAME]: MessageEmbed field names must be non-empty strings.

at Util.verifyString (C:\Users\x\OneDrive\Desktop\Software\Discord-Mirror\node_modules\discord.js-selfbot-v13\src\util\Util.js:462:49)

at MessageEmbed.normalizeField (C:\x\bramd\OneDrive\Desktop\Software\Discord-Mirror\node_modules\discord.js-selfbot-v13\src\structures\MessageEmbed.js:554:18)

at C:\Users\x\OneDrive\Desktop\Software\Discord-Mirror\node_modules\discord.js-selfbot-v13\src\structures\MessageEmbed.js:576:14

at Array.map (<anonymous>)

at MessageEmbed.normalizeFields (C:\Users\x\OneDrive\Desktop\Software\Discord-Mirror\node_modules\discord.js-selfbot-v13\src\structures\MessageEmbed.js:575:8)

at MessageEmbed.setup (C:\Users\x\OneDrive\Desktop\Software\Discord-Mirror\node_modules\discord.js-selfbot-v13\src\structures\MessageEmbed.js:107:91)

at new MessageEmbed (C:\Users\x\OneDrive\Desktop\Software\Discord-Mirror\node_modules\discord.js-selfbot-v13\src\structures\MessageEmbed.js:45:10)

at C:\Users\x\OneDrive\Desktop\Software\Discord-Mirror\node_modules\discord.js-selfbot-v13\src\structures\MessagePayload.js:264:49

at Array.map (<anonymous>)

at MessagePayload.resolveData (C:\Users\x\OneDrive\Desktop\Software\Discord-Mirror\node_modules\discord.js-selfbot-v13\src\structures\MessagePayload.js:264:36) {

[Symbol(code)]: 'EMBED_FIELD_NAME'

}
