### ISSUE TITLE
Webhook issue

### ISSUE THREAD

**Issue by chill-c0der2** [crimilo/Discord-Mirror#80]
if (!url || url.length <= 1) throw new Error('WEBHOOK_URL_INVALID');
                                   ^

Error [WEBHOOK_URL_INVALID]: The provided webhook URL is not valid.
    at new WebhookClient (/home/pwn/Discord-Mirror/node_modules/discord.js-selfbot-v13/src/client/WebhookClient.js:36:42)
    at Mirror.loadWebhooks (/home/pwn/Discord-Mirror/dist/mirror.js:121:32)
    at new Mirror (/home/pwn/Discord-Mirror/dist/mirror.js:27:14)
    at MirrorClient.loadMirror (/home/pwn/Discord-Mirror/dist/client.js:91:24)
    at MirrorClient.loadMirrors (/home/pwn/Discord-Mirror/dist/client.js:83:18)
    at new MirrorClient (/home/pwn/Discord-Mirror/dist/client.js:17:14)
    at Object.<anonymous> (/home/pwn/Discord-Mirror/dist/index.js:6:16)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32) {
  [Symbol(code)]: 'WEBHOOK_URL_INVALID'

**Comment by crimilo** [comment]
u configured an invalid url. fix it and restart the bot.
